### ISSUE TITLE
Wrong/missing CSRF ?!

### ISSUE THREAD

**Issue by digitusmalus** [arlogn/easyshare#12]
For some days I get an error message that my post cannot be sent while trying to share something via easyshare. Then Diaspora (diasp.de) logs me out an sends four (!) of the following mails:

> Hello digitus,
>
> We received a request with a wrong/missing CSRF token from your account. To prevent any possible damage you have been logged out.
>
> For more information on CSRF see https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)
>
> Sorry,
>
> The diaspora* email robot!

What's going wrong?

Greetings,
Andreas

**Comment by arlogn** [comment]
yeah, it seems the addon fails to get the token and the request is sent with a wrong header (and diaspora sends a warning). I'm writing a new version which fix the issue and improves the sending of a status message. You will have the update soon.

**Comment by victorhck** [comment]
same here! ;)
I'll wait your update! And many thanks for your work!!!

**Comment by arlogn** [comment]
Well, I've uploaded today the new version on AMO and it will be made available soon. Since most of the code has been refactored, when you will receive the upgrade, please let me know if all it's okay. Thanks.

**Comment by victorhck** [comment]
Thanks to you!! :+1: 
Your code, it's a great tool to use and share in Diaspora* !!
Thanks!

**Comment by digitusmalus** [comment]
Thank you! When will the new version be available on addons.mozilla.org?

**Comment by arlogn** [comment]
@digitusmalus it depends by the queue, all updates must be verified by a Mozilla reviewer. Usually a few days.

**Comment by victorhck** [comment]
updated right now. Noy mayor issues here...

only the interface now looks a bit extrange in my openSUSE+Plasma system. ¿?

![1](https://cloud.githubusercontent.com/assets/1514206/20350612/dc51fc0e-ac0f-11e6-86bb-87f536b20ebf.png)

**Comment by arlogn** [comment]
Looks good, I renewed the panel with a dual color background. :)

**Comment by digitusmalus** [comment]
Works fine here ... thanks for fixing this issue :)

**Comment by victorhck** [comment]
ah! then it's ok!!
Thanks a lot!!
BTW, do you have an account in Diaspora? do I follow you? :)
bye!

**Comment by arlogn** [comment]
You can find me on diaspora by searching for _arlogn_.
Thanks for your feedback.
