### ISSUE TITLE
The Return of "Wrong/missing CSRF ?! #12"

### ISSUE THREAD

**Issue by digitusmalus** [arlogn/easyshare#14]
Unfortunately the issue with the Wrong/missing CSRF returned :(

https://github.com/arlogn/easyshare/issues/12

Same error message and you aren't able to post via EasyShare again.

Greetings,
Andreas

**Comment by arlogn** [comment]
Maybe caused by some changes to the diaspora code in the last update (0.6.2.0). I will try to fix it in the next days.

**Comment by arlogn** [comment]
It's weird, I tried the addon with the latest diaspora version and seems okay.
Please, try this:
1. disable the addon in the addon manager (about:addons)
2. close firefox
3. restart firefox
4. enable the addon

If the above doesn't solve, try this:
1. close firefox
2. open `~/.mozilla/firefox/<your_profile>/jetpack/jid1-gqfeTXcouyVkpg@jetpack/simple-storage`
3. delete `store.json`
4. restart firefox

**Comment by digitusmalus** [comment]
I do not know what the problem was, but today it worked here too ... without any intervention :/
Thank you for the good work.
Greetings,
Andreas

**Comment by digitusmalus** [comment]
Maybe it's a Problem of the URL.
When I try to share the picture: https://www.taz.de/scripts/tom/gif.php?t=tom&d=1481890124 the error appears and I receive the Wrong/missing CSRF-Mail again.

Greetings,
Andreas

**Comment by digitusmalus** [comment]
Please, try this:

>     disable the addon in the addon manager (about:addons)
>     close firefox
>     restart firefox
>     enable the addon

OK. This solved the problem this time.

Sort of hiccup ;)

**Comment by arlogn** [comment]
Yeah sure, the problem is probably caused by an invalid image file. The url above refers to a php document and not to an image. The selector of the context-menu does not check whether the src attribute of the <img> tag is really a valid image file. I'll have to test and perhaps add a check in the next update. Thanks.
