### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by victorhck** [arlogn/easyshare#15]
Hello!

I updated my SO (openSUSE Tumbleweed + Plasma) and Firefox updated to 51.0.1 and now if I want to share an article in my Diaspora* account via EasyShare I get this error.

¿Can I submit more information to help you?

Thanks...

**Comment by arlogn** [comment]
Yeah, this is due by the upgrade to Firefox 51.  I already know how to fix it and tomorrow I will send the upgrade on AMO.

Note:
after the upgrade Easyshare it will only work with Firefox >= 51. If someone want to use it with an older firefox version have to skip the upgrade.

**Comment by victorhck** [comment]
Seems to works fine here!!
Thanks a lot!!
