### ISSUE TITLE
Return of "Wrong/missing CSRF" again ?! (see #12 #14)

### ISSUE THREAD

**Issue by digitusmalus** [arlogn/easyshare#17]
With the new Version 0.14.1 the CSRF-issue appears again.

I still use FF 56 since Manjaro Linux hasn't updated yet.

Any ideas?

Greetings (and Thanx for this great Addon),
Andreas

**Comment by arlogn** [comment]
There is a little bug, the session counter not reset and the addon does not download a new token when needed. I don't know if the problem comes from there.
You can try to save again the preferences. This forces the addon to login and download a new token.
Let me know if this solves.

**Comment by digitusmalus** [comment]
No. Unfortunately it doesn't solve the problem :(

**Comment by arlogn** [comment]
Well, as soon as I can I try to fix the problem.

**Comment by arlogn** [comment]
I've been testing the addon with FF56 and FF57, on my development env and on several pods but I could not replicate the issue. I pushed on branch _webextension_ an update that should fix it. If you want you can test it in this way:

1. unzip easyshare_0.14.2_test.zip in a folder
2. open firefox with a new profile
3. enter about:debugging
4. push the button 'Load a temporary addon' and choose the file manifest.json from the extracted files
5. test the addon (you can also opening a debug window)

Let me know if it works properly. Thanks.

**Comment by digitusmalus** [comment]
> ERROR: /home/andi/Desktop/easyshare_0.14.2_test.zip : /home/andi/Desktop/easyshare_0.14.2_test.zip
ERROR: Can not open the file as [zip] archive


> ERRORS:
Is not archive

:(

**Comment by arlogn** [comment]
I removed the archive and edited the last response. Use the 'Clone or Download' button and follow the steps to test.

**Comment by digitusmalus** [comment]
I'm sorry, but where do I find the "'Clone or Download' button"?

**Comment by arlogn** [comment]
https://github.com/arlogn/easyshare/tree/webextension
The green button in the above page.

**Comment by arlogn** [comment]
Uploaded a new version 0.14.2 on AMO. I hope it fix your problem.

**Comment by digitusmalus** [comment]
I'm sorry. Unfortunately it didn't solve the problem :(
Am I the only one with this problem?

**Comment by arlogn** [comment]
It seems so. I'm sorry.
What happens when you try to get your aspects?

**Comment by digitusmalus** [comment]
Same error "(SignIn) invalid username or password" ...
I doublechecked username & pw :)

**Comment by digitusmalus** [comment]
If I find some time, I'll check with a new profile ... maybe it's some strange interaction with another addon ...

**Comment by arlogn** [comment]
Maybe the problem is the cookie. Please, try to remove it. Open the Firefox Preferences, select the Privacy & Security panel and go to the History section. Open the cookie's list and find the cookie of your pod (diasp.de?). Select it and click Remove selected.

**Comment by digitusmalus** [comment]
No effect :(

**Comment by digitusmalus** [comment]
Very strange: On my notebook (TP X100e, FF 57, same addons synced, same OS Manjaro Linux) EasyShare works flawlessly ...

**Comment by arlogn** [comment]
You could try doing the reverse process. Rename the .mozilla folder in your desktop home and try synchronizing with your notebook.

**Comment by digitusmalus** [comment]
btw: not completely flawlessly. The content is posted to Diaspora but afterwards the CSRF-error occurs.

**Comment by arlogn** [comment]
Very very strange ...

**Comment by victorhck** [comment]
To the record: No problems over here...

**Comment by arlogn** [comment]
This was definitely fixed. 
84a699be9e19dc813b456d180d1fcda02a7a4c50
21744bb6b0d716b4a920ced8297c2936e5780732
