### ISSUE TITLE
"Authentification error"

### ISSUE THREAD

**Issue by Sim59121** [arlogn/easyshare#19]
Hello,

I have install diapora easyshare 0.16.1
But, i have a problem.

I select text, and i make a right click. I click on share this content.
And when i click on "send", i have a error message "authentification failed".

But,i check and  i'm log in diapora easyshare...
It's the correct domain, login and password...

![bug diapora](https://user-images.githubusercontent.com/37774026/42134458-888ed5e2-7d3c-11e8-8a68-3da6bf86b9b2.png)
![bug diapora png 1](https://user-images.githubusercontent.com/37774026/42134459-88bd42ec-7d3c-11e8-8642-0b08b2af56e0.png)

Can you help me please?
regards,

**Comment by arlogn** [comment]
The username seems wrong. You have to enter the username of your diaspora handle (diaspora ID). The above seems an email address.
example:
my pod is social.mbuto.me
my diaspora handle is podmin@social.mbuto.me
my diaspora username is 'podmin'

You can find the diaspora ID in Settings, below "Your diaspora* ID".

**Comment by Sim59121** [comment]
Ok, i try my diaspora ID, Thank you !
But, the bug is already  !

![bug diapora png 2](https://user-images.githubusercontent.com/37774026/42136655-dda68674-7d5f-11e8-8d44-6d71641431fb.png)

**Comment by arlogn** [comment]
OK, your username is **sim59121**

**Comment by Sim59121** [comment]
Ok, but i try sim59121 AND sim59121@pod.bruniau.net
When is sign in with sim59121 or sim59121@pod.bruniau.net, 
the error message is already !

**Comment by arlogn** [comment]
Login to your pod. Then retry to send a post with Easyshare with the right username and password.
Let me know if this solve.

**Comment by Sim59121** [comment]
Ok.
I'm log in my pod and i share a post in diaspora with easy share.

But...  The post is not send in diaspora...
The error message is already present.

**Comment by arlogn** [comment]
Is you the podmin of this pod? If yes, can you create a temporary account for me?

In the meantime try to remove all cookies from the Firefox Preferences.
Or try to create a new clean profile from _about:profiles_. Create it and start a new browser with this profile. Install the addon e retry.

**Comment by Sim59121** [comment]
No, i'm not the pod admin. Sorry !
But i speak with the pod admin and he check. For the pod admin my account is ok and the pod is ok...

I don't understand the problem...

**Comment by arlogn** [comment]
I suggested you try a new profile to see if the problem is caused by another addon. You can also try to disable them all to verify it.
Your pod is definitely OK, I just wanted try to see if the problem also occurred with Linux because honestly I have never tested the addon on Windows.
Later I will create a test account for you on my pod and send you the credentials by email. Let's try this test too.

**Comment by Sim59121** [comment]
Ok,
It's ok for a test account on your pod.
And yes, i'm on Windows.

**Comment by arlogn** [comment]
mail sent to the address you entered in the first screenshot.

**Comment by Sim59121** [comment]
Ok, thank you arlogn !
i test with your pod and the error is already present.

I made 3 screenshot :  The setting of easysharre, and the "inspector" and the "console" (it's in the windows of debug).


![bug diaspora png 6](https://user-images.githubusercontent.com/37774026/42149165-5f8d1f0c-7dd5-11e8-91f1-b3c453009dae.png)

![bug diaspora png 4](https://user-images.githubusercontent.com/37774026/42149098-1fbf0f7a-7dd5-11e8-942d-c9d34c0c0694.png)

![bug diaspora png 5](https://user-images.githubusercontent.com/37774026/42149099-1fe6ffda-7dd5-11e8-8260-1c19d7063559.png)

Thank you for your help !
Regard,

**Comment by arlogn** [comment]
The above console isn't easyshare debugging.

From about:debugging:

![debug](https://user-images.githubusercontent.com/914785/42163141-aedbc8f2-7e01-11e8-9602-21429168db1b.jpg)

If you open the right debug console you have to view the log string "Easyshare menu created successfully" inside it.

Then, login to https://social.mbuto.me with the browser and enter the credentials I sent you.
When you are logged in and can view the diaspora stream try to send a text with the easyshare publisher. If an error occurs must be logged in the console.

Thanks

**Comment by Sim59121** [comment]
Hello,

I click on "deboguer" and i don't see the log "easyshare menu created successfully"...
I'm log on https://social.mbuto.me and i send a post.

But the error is already present !
It's crazy...  ;-(

![bug diaspora png 8](https://user-images.githubusercontent.com/37774026/42165048-ba826aac-7e07-11e8-80db-3468c8782d3e.png)

![bug diaspora png 7](https://user-images.githubusercontent.com/37774026/42164043-0d6db292-7e05-11e8-989d-a828deeb28fa.png)

![bug diaspora png 9](https://user-images.githubusercontent.com/37774026/42165210-f09fd17e-7e07-11e8-90ba-a2453e9a6b10.png)

**Comment by arlogn** [comment]
It seems the addon isn't debugged. I cannot understand what happens. The only suggest is to create a clean profile because I view you have a lot of extensions.
Type about:profiles
Create a new profile named TEST
Close firefox
Restart firefox and select the new profile TEST
Install the addon, send something and check if now the debug console contains errors.
After that you can remove the TEST profile.

The console should contains something like that:

![debug](https://user-images.githubusercontent.com/914785/42170464-dde2fc50-7e16-11e8-9669-8d1223113a72.jpg)

and errors if something went wrong.
The screenshot is the debugging of a test carried out in the manner described above, creating a new profile. And as you can see in the test8 account stream, all is gone good.

**Comment by Sim59121** [comment]
Ok, thank you for your help.
Can you delete my account on your domain please ?

**Comment by arlogn** [comment]
Account deleted.

Poor informations to understand what causes the issue.
The addon should be tested on Windows.

**Comment by Sim59121** [comment]
Ok, Thank you ! ;-)
