### ISSUE TITLE
Network Request failed

### ISSUE THREAD

**Issue by RoyTheNewbie** [arlogn/easyshare#23]
I have just installed your EasyShare add-on to my Firefox browser. 

I see the toolbar Easyshare icon and the entry in the right-click menu is displayed. Both open up the pop-up window. I can then write a post,linking to images text,etc. 

**BUT**....I cannot display my Aspects or Send the post to the Public. In each case, I get a red "_Network request failed message_". I have entered my loginID and password correctly so I don't know what I am doing wrong.
Can you please advise?
Thank you in advance.

**Comment by arlogn** [comment]
What is your pod?
Can you open the page `https://your.pod/bookmarklet`? This is the page where the addon retrieves the aspect list.

**Comment by RoyTheNewbie** [comment]
Well, I did confirm that the bookmarklet worked.I had been musing about what I thought I could be doiung wrong.Then it came to me......_I had made an elementary mistake in entering my login credentials_. My pod is _pluspora_ and for the requested pod URL I had entered _pluspora.com_ whereas I should have entered _https://pluspora.com_.
I do apologise for my simple error!

Thank you for replying and for creating what I think will be a very useful add-on.

**Comment by victorhck** [comment]
Maybe can be added a _italic_ text like an exaple. Maybe something like: _"https://podexaple.com"_ or something like that...

**Comment by RoyTheNewbie** [comment]
@victorhck The add-on is now working for me, as I explained in my last post.My error was in not inserting the _https://_ at the start of the pod's URL.
I really like this Easyshare add-on!
